# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 21:25
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import internationalflavor.iban.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2, message='2 or more characters required.')])),
                ('lastname', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2, message='2 or more characters required.')])),
                ('iban', internationalflavor.iban.models.IBANField(unique=True, verbose_name='IBAN')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
