# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-12 17:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20170711_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmodel',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created'),
        ),
    ]
